FROM shrinand/k8s-minion-manager:v0.1

RUN apt-get install make && \
    pip install --upgrade pip && \
    pip install pytest && \
    pip install mock && \
    pip install moto

ENV PYTHONPATH=/
WORKDIR /src
